-- Adds a URL slug to each cocktail for the Phase 3 recipe-card route
-- (/cocktails/[slug]). Values were generated from seed-data/cocktails.json
-- with src/lib/slug.ts's slugify() (see its unit tests, which also assert
-- all 100 are unique). Stored rather than computed at request time so a
-- cocktail's URL stays stable even if its display name is later edited.

alter table public.cocktails add column slug text;

update public.cocktails c
set slug = v.slug
from (values
  ('Rum Fruit Cup (Difford''s Cup No.4)', 'rum-fruit-cup-diffords-cup-no-4'),
  ('Mai Tai (Difford''s recipe)', 'mai-tai-diffords-recipe'),
  ('Three Dots and a Dash', 'three-dots-and-a-dash'),
  ('Navy Grog', 'navy-grog'),
  ('Firecracker', 'firecracker'),
  ('Mai Tai (Trader Vic''s)', 'mai-tai-trader-vics'),
  ('Painkiller', 'painkiller'),
  ('Saturn', 'saturn'),
  ('Aku Aku', 'aku-aku'),
  ('Missionary''s Downfall', 'missionarys-downfall'),
  ('Drunken Helmsman', 'drunken-helmsman'),
  ('Elusive Dreams', 'elusive-dreams'),
  ('Tiki Max', 'tiki-max'),
  ('Undead Gentleman', 'undead-gentleman'),
  ('Jungle Bird', 'jungle-bird'),
  ('Nuclear Daiquiri', 'nuclear-daiquiri'),
  ('Tia Mia', 'tia-mia'),
  ('Hawaiian Stone Sour', 'hawaiian-stone-sour'),
  ('Pineapple Daiquiri (on-the-rocks)', 'pineapple-daiquiri-on-the-rocks'),
  ('Mr. Bali Hai', 'mr-bali-hai'),
  ('Zombie', 'zombie'),
  ('Fog Cutter (Bramble style)', 'fog-cutter-bramble-style'),
  ('Près du Quai', 'pres-du-quai'),
  ('Menehune Juice', 'menehune-juice'),
  ('Pinky Pincher', 'pinky-pincher'),
  ('Halekulani', 'halekulani'),
  ('Bahama Mama', 'bahama-mama'),
  ('Gun Club Punch No.1', 'gun-club-punch-no-1'),
  ('Bahamas Daiquiri', 'bahamas-daiquiri'),
  ('Honolulu Cocktail No. 1', 'honolulu-cocktail-no-1'),
  ('Poison Dart', 'poison-dart'),
  ('Nuka Nuka', 'nuka-nuka'),
  ('Pago Pago', 'pago-pago'),
  ('Sleeping Lotus', 'sleeping-lotus'),
  ('Ranglum', 'ranglum'),
  ('Yellow Bird', 'yellow-bird'),
  ('Fay Wray', 'fay-wray'),
  ('Goombay Smash', 'goombay-smash'),
  ('Quarantine Order', 'quarantine-order'),
  ('St. Stephen''s Sour', 'st-stephens-sour'),
  ('Fog Cutter', 'fog-cutter'),
  ('Barracuda', 'barracuda'),
  ('The Conference', 'the-conference'),
  ('Pinky Gonzales', 'pinky-gonzales'),
  ('Crystal Ship', 'crystal-ship'),
  ('Lioness', 'lioness'),
  ('Jet Pilot', 'jet-pilot'),
  ('Nui Nui', 'nui-nui'),
  ('Kamaniwanalaya', 'kamaniwanalaya'),
  ('In the August Sun', 'in-the-august-sun'),
  ('Western Sour', 'western-sour'),
  ('Private Island', 'private-island'),
  ('Lost Lake', 'lost-lake'),
  ('Shark''s Tooth (by Don Beach)', 'sharks-tooth-by-don-beach'),
  ('Humuhumunukunukuapua''a', 'humuhumunukunukuapuaa'),
  ('Snake Eyes', 'snake-eyes'),
  ('Rum Cow', 'rum-cow'),
  ('Rye Tai', 'rye-tai'),
  ('Daiquiri De Luxe', 'daiquiri-de-luxe'),
  ('Hawaiian Eye', 'hawaiian-eye'),
  ('Mai Dutch Tai', 'mai-dutch-tai'),
  ('Roxie Ray', 'roxie-ray'),
  ('Electric Avenue', 'electric-avenue'),
  ('Lion of Baltimore', 'lion-of-baltimore'),
  ('Scorpion Reef', 'scorpion-reef'),
  ('Rum Dum Sour', 'rum-dum-sour'),
  ('Rumshack Punch', 'rumshack-punch'),
  ('Tapa Punch', 'tapa-punch'),
  ('Royal Daiquiri', 'royal-daiquiri'),
  ('Totally Tropical Mai Tai', 'totally-tropical-mai-tai'),
  ('Funk The Funky Funk', 'funk-the-funky-funk'),
  ('Hawaiian (by Thad Vogler)', 'hawaiian-by-thad-vogler'),
  ('3 Monkeys & a dash', '3-monkeys-and-a-dash'),
  ('Major Bailey No. 2', 'major-bailey-no-2'),
  ('Hornitos Lau', 'hornitos-lau'),
  ('Vacation Martini', 'vacation-martini'),
  ('Will Of Alan', 'will-of-alan'),
  ('Snowbird', 'snowbird'),
  ('East India No. 3', 'east-india-no-3'),
  ('Brooklyn Burro', 'brooklyn-burro'),
  ('Three of Strong', 'three-of-strong'),
  ('USS Wondrich', 'uss-wondrich'),
  ('Rum Barrel (by Donn Beach)', 'rum-barrel-by-donn-beach'),
  ('Tropical Pineapple Daiquiri', 'tropical-pineapple-daiquiri'),
  ('Blue Hawaii', 'blue-hawaii'),
  ('Suffering Bastard', 'suffering-bastard'),
  ('Doctor Funk', 'doctor-funk'),
  ('Ancient Mariner', 'ancient-mariner'),
  ('Scorpion', 'scorpion'),
  ('Honi Honi', 'honi-honi'),
  ('Rum Runner', 'rum-runner'),
  ('Suit & Tai', 'suit-and-tai'),
  ('Royal Hawaiian', 'royal-hawaiian'),
  ('Major Bailey', 'major-bailey'),
  ('Fernet Me Not No. 3', 'fernet-me-not-no-3'),
  ('Honolulu', 'honolulu'),
  ('Caribbean Punch', 'caribbean-punch'),
  ('Montego Bay', 'montego-bay'),
  ('Swamp Water', 'swamp-water'),
  ('Hawaiian Iced Tea', 'hawaiian-iced-tea')
) as v(name, slug)
where c.name = v.name;

alter table public.cocktails alter column slug set not null;
alter table public.cocktails add constraint cocktails_slug_key unique (slug);
alter table public.cocktails add constraint cocktails_slug_format
  check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$');

comment on column public.cocktails.slug is 'URL slug for /cocktails/[slug]; generated once from name by src/lib/slug.ts slugify().';
